Repository kieler/RailTrail, pull requests merged in 2023-09, with the labels that each got.

#115 #91: Fixed mutation of certain array functions
  Server/src/services/poi.service.ts
  Server/src/services/vehicle.service.ts
Labels: bug, backend

#119 #90: Added logging to services
  Server/src/services/poi.service.ts
  Server/src/services/track.service.ts
  Server/src/services/vehicle.service.ts
Labels: backend

#112 64 backend refining database connection
  Server/prisma/schema.prisma
  Server/src/routes/poi.route.ts
  Server/src/routes/poitype.route.ts
  Server/src/routes/tracker.route.ts
  Server/src/routes/vehicle.route.ts
  Server/src/routes/vehicletype.route.ts
  Server/src/services/db/log.controller.ts
  Server/src/services/db/poi.controller.ts
  Server/src/services/db/track.controller.ts
  Server/src/services/db/tracker.controller.ts
  Server/src/services/db/user.controller.ts
  Server/src/services/db/vehicle.controller.ts
  Server/src/services/login.service.ts
  Server/src/services/poi.service.ts
  Server/src/services/track.service.ts
  Server/src/services/user.service.ts
  Server/src/services/vehicle.service.ts
Labels: enhancement, backend

#124 109 adjust time interval for position computation
  Server/src/services/vehicle.service.ts
Labels: backend

#140 #114: Replaced getNearbyVehicles
  Server/src/routes/vehicle.route.ts
  Server/src/services/vehicle.service.ts
Labels: backend

#142 133 remove getvehicletrackdistancekm and move getvehicletrackdistancepercentage
  Server/src/routes/track.route.ts
  Server/src/routes/vehicle.route.ts
  Server/src/services/track.service.ts
  Server/src/services/vehicle.service.ts
Labels: backend

#146 User management in the Frontend
  Server/src/routes/user.route.ts
  Server/src/services/user.service.ts
  Website/src/app/components/base_layout.tsx
  Website/src/app/components/dynlist.tsx
  Website/src/app/components/dynmap.tsx
  Website/src/app/components/header.tsx
  Website/src/app/components/login.tsx
  Website/src/app/components/login_wrap.tsx
  Website/src/app/components/username-provider.tsx
  Website/src/app/layout.tsx
  Website/src/app/login/page.tsx
  Website/src/app/management/components/iconSelection.tsx
  Website/src/app/management/components/inputWithLabel.tsx
  Website/src/app/management/components/managementForm.tsx
  Website/src/app/management/components/referencedObjectSelect.tsx
  Website/src/app/management/components/styledSelect.tsx
  Website/src/app/management/components/submitButtons.tsx
  Website/src/app/management/myself/client.tsx
  Website/src/app/management/myself/page.tsx
  Website/src/app/management/page.tsx
  Website/src/app/management/poi/client.tsx
  Website/src/app/management/poiTypes/client.tsx
  Website/src/app/management/trackers/client.tsx
  Website/src/app/management/users/client.tsx
  Website/src/app/management/users/deleteUser.tsx
  Website/src/app/management/users/page.tsx
  Website/src/app/management/vehicles/client.tsx
  Website/src/app/signup/page.tsx
  Website/src/app/webapi/auth/route.ts
  Website/src/app/webapi/tracker/delete/[trackerID]/route.ts
  Website/src/app/webapi/user/changePassword/route.ts
  Website/src/app/webapi/user/changeUsername/route.ts
  Website/src/app/webapi/user/create/route.ts
  Website/src/app/webapi/user/delete/[username]/route.ts
  Website/src/app/webapi/user/list/route.ts
  Website/src/pages/_document.tsx
  Website/src/pages/logout.tsx
  Website/src/utils/data.ts
  Website/src/utils/fetcher.ts
Labels: web

#150 127 [Backend] Seeding of Database
  Server/.env
  Server/package.json
  Server/prisma/seed.ts
  Server/tsconfig.json
Labels: enhancement, backend

#151 128 [Backend] Refinenment of Deletion for Vehicles, VehicleTypes and POIs
  Server/prisma/schema.prisma
  Server/src/services/db/vehicle.controller.ts
Labels: enhancement, backend

#147 139 backend remove redundant calculations and database queries
  Server/src/routes/track.route.ts
  Server/src/routes/vehicle.route.ts
  Server/src/services/vehicle.service.ts
Labels: backend

#168 154 compute vehicle data all at once
  Server/src/routes/track.route.ts
  Server/src/routes/tracker.route.ts
  Server/src/routes/vehicle.route.ts
  Server/src/services/track.service.ts
  Server/src/services/vehicle.service.ts
Labels: backend

#171 170 error handling in services
  Server/src/routes/init.route.ts
  Server/src/routes/poi.route.ts
  Server/src/routes/track.route.ts
  Server/src/services/poi.service.ts
  Server/src/services/track.service.ts
  Server/src/services/vehicle.service.ts
  Server/src/utils/geojsonUtils.ts
Labels: backend

#173 169 fix vehicle data computation
  Server/src/services/vehicle.service.ts
Labels: backend

#174 118 refactor computation for vehicle heading
  Server/src/services/track.service.ts
  Server/src/services/vehicle.service.ts
Labels: backend
