Repository kieler/RailTrail, pull requests merged in 2023-08, with the labels that each got.

#43 Added a list of vehicles
  Website/src/app/add_track/page.tsx
  Website/src/app/components/base_layout.tsx
  Website/src/app/components/dynlist.tsx
  Website/src/app/components/dynmap.tsx
  Website/src/app/components/form.tsx
  Website/src/app/components/globals.css
  Website/src/app/components/loadmap.tsx
  Website/src/app/components/login.tsx
  Website/src/app/components/login_wrap.tsx
  Website/src/app/components/map.tsx
  Website/src/app/components/track_selection.tsx
  Website/src/app/layout.tsx
  Website/src/app/list/page.tsx
  Website/src/app/login/page.tsx
  Website/src/app/map/page.tsx
  Website/src/app/page.tsx
  Website/src/app/select_track/page.tsx
  Website/src/app/signup/page.tsx
  Website/src/app/webapi/auth/route.ts
  Website/src/app/webapi/tracks/list/route.ts
  Website/src/app/webapi/tracks/new/route.ts
  Website/src/app/webapi/update/route.ts
  Website/src/components/form.tsx
  Website/src/components/layout.tsx
  Website/src/components/map.tsx
  Website/src/pages/_app.tsx
  Website/src/pages/_document.tsx
  Website/src/pages/logout.tsx
  Website/src/utils/api.website.ts
  Website/src/utils/common.ts
  Website/src/utils/data.ts
  Website/src/utils/helpers.ts
  Website/src/utils/types.ts
Labels: web

#61 59 adjust services for database changes
  Server/package-lock.json
  Server/package.json
  Server/prisma/schema.prisma
  Server/src/models/user.ts
  Server/src/routes/init.route.ts
  Server/src/routes/poi.route.ts
  Server/src/routes/users.route.ts
  Server/src/routes/vehicles.route.ts
  Server/src/routes/vehicletypes.route.ts
  Server/src/services/db/log.controller.ts
  Server/src/services/db/poi.controller.ts
  Server/src/services/db/track.controller.ts
  Server/src/services/db/tracker.controller.ts
  Server/src/services/db/user.controller.ts
  Server/src/services/db/vehicle.controller.ts
  Server/src/services/poi.service.ts
  Server/src/services/track.service.ts
  Server/src/services/tracker.service.ts
  Server/src/services/user.service.ts
  Server/src/services/vehicle.service.ts
  Server/src/utils/geojsonUtils.ts
Labels: enhancement, backend

#50 23 service improvements
  Server/src/routes/init.route.ts
  Server/src/routes/track.route.ts
  Server/src/services/db/log.controller.ts
  Server/src/services/poi.service.ts
  Server/src/services/track.service.ts
  Server/src/services/vehicle.service.ts
  Server/src/utils/geojsonUtils.ts
Labels: enhancement, backend

#96 94 adjust service function calls for new function signatures
  Server/src/routes/vehicle.route.ts
  Server/src/services/poi.service.ts
  Server/src/services/vehicle.service.ts
Labels: backend

#98 23 service improvements v2
  Server/src/routes/init.route.ts
  Server/src/routes/login.route.ts
  Server/src/routes/poi.route.ts
  Server/src/routes/track.route.ts
  Server/src/routes/tracker.route.ts
  Server/src/routes/vehicle.route.ts
  Server/src/services/db/log.controller.ts
  Server/src/services/db/tracker.controller.ts
  Server/src/services/poi.service.ts
  Server/src/services/track.service.ts
  Server/src/services/tracker.service.ts
  Server/src/services/vehicle.service.ts
  Server/src/utils/geojsonUtils.ts
  Server/src/utils/please_dont_crash.ts
Labels: backend
